### GET /feed/posts
@GET_POST_JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pdW1pdUB4cncuaW8iLCJ1c2VySWQiOiI2NDhmMTYxODhiZjJkN2U1MjRjODI5ODUiLCJpYXQiOjE2ODcxMDczNTYsImV4cCI6MTY4NzExMDk1Nn0.ti1iqcCCOqzHFNQngAPjqQDFvJUKafcTGstyHb1qpfw

GET http://localhost:3030/feed/posts
Authorization: Bearer {{GET_POST_JWT}}

### POST /food/posts

POST http://localhost:3030/feed/posts
Content-Type: application/json

{
  "title": "New Post Title",
  "content": "New Post Content"
}

### GET /feed/post
@FEED_POST_ID = 648e3e379c6489c6caed75b3

GET http://localhost:3030/feed/post/{{FEED_POST_ID}}


### POST /auth/signup
@SIGN_UP_EMAIL = miumiu@xrw.io
@SIGN_UP_USERNAME = miumiu
@SIGN_UP_PASSWORD = adminAb1

POST http://localhost:3030/auth/signup
Content-Type: application/json

{
  "email": "{{SIGN_UP_EMAIL}}",
  "password": "{{SIGN_UP_PASSWORD}}",
  "username": "{{SIGN_UP_USERNAME}}"
}

### POST /auth/login
@LOGIN_IN_EMAIL = miumiu@xrw.io
@LOGIN_IN_PASSWORD = adminAb1

POST http://localhost:3030/auth/login
Content-Type: application/json

{
  "email": "{{SIGN_UP_EMAIL}}",
  "password": "{{SIGN_UP_PASSWORD}}"
}
