###
GET http://localhost:3030/admin/add-product

###
GET http://localhost:3030/admin/products

### admin/edit-product/:productId
GET http://localhost:3030/admin/edit-product/6485d9aa98a7a7f47c0e146c

### products/:productId
DELETE http://localhost:3030/admin/products/648654e8c7ed7ec9127d4f08


### admin/add-product
@title = Noodle
@price = 11.11
@imageUrl = NoodleUrl
@description = Tasty Noodle

POST http://localhost:3030/admin/add-product
Content-Type: application/x-www-form-urlencoded

title={{title}}&price={{price}}&imageUrl={{imageUrl}}&description={{description}}

### admin/edit-product
@title = CookieAAA
@price = 44.44
@imageUrl = CookieUrl
@description = Tasty Cookie
@id = 648654e8c7ed7ec9127d4f08

POST http://localhost:3030/admin/edit-product
Content-Type: application/x-www-form-urlencoded

title={{title}}&price={{price}}&imageUrl={{imageUrl}}&description={{description}}&id={{id}}


### product
GET http://localhost:3030/products

### product/:productId
@product = 648654e8c7ed7ec9127d4f08

GET http://localhost:3030/products/{{product}}

### cart
@post_card_productId = 64866458212163db582d3784

POST http://localhost:3030/cart
Content-Type: application/x-www-form-urlencoded

productId={{post_card_productId}}

### get /cart
GET http://localhost:3030/cart

### post /cart-delete-item
@cart-delete-item_productId = 64866458212163db582d3784

POST http://localhost:3030/cart-delete-item
Content-Type: application/x-www-form-urlencoded

productId={{cart-delete-item_productId}}

### post /create-order

POST http://localhost:3030/create-order


### post /order

GET http://localhost:3030/order

### GET /login

GET http://localhost:3030/login
# Cookie: loggedIn=true

### POST /login
POST http://localhost:3030/login

### POST /login
POST http://localhost:3030/logout