GET http://localhost:3030/admin/add-product


###
@title = Noodle
@price = 11.11
@imageUrl = NoodleUrl
@description = Tasty Noodle

POST http://localhost:3030/admin/add-product
Content-Type: application/x-www-form-urlencoded

title={{title}}&price={{price}}&imageUrl={{imageUrl}}&description={{description}}